version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:30"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 10
  labels:
    - front-end
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
